version: "3.7"

services:
  example:
    # user: '1001:121'
    build:
      context: .
    volumes:
      - reports:/home/reports
    command: ["touch /home/reports/test.txt"]

volumes:
  reports:

# id inside docker: uid=1000 gid=1000
# id of runner: uid=1001 gid=121