version: "3.7"

services:
  example:
    # user: '1000:1000'
    build:
      context: .
    volumes:
      - reports:/home/reports:z
    command: ["touch /home/reports/test.txt"]

volumes:
  reports: